### ISSUE TITLE
115小助手

### ISSUE THREAD

**Issue by zengruzhen** [maomao1996/tampermonkey-scripts#10]
使用115的时候感觉挺需要“在新标签打开文件夹”这个功能，因为从根列表进入一个文件夹再返回，这个操作需要重新拉数据挺慢的。而且重新拉的根列表又回到滚屏的最上面了，很不方便。

**Comment by zengruzhen** [comment]
目前使用小助手的一键搜可以勉强达到这个效果

**Comment by maomao1996** [comment]
这个我要看看是在悬浮按钮上加一个在新标签页打开，还是修改原有的跳转

**Comment by zengruzhen** [comment]
隔壁优化大师也有类似的评论
![image](https://user-images.githubusercontent.com/18514089/210158878-554545f0-9abf-4d90-baa8-ae2287d8019f.png)

**Comment by maomao1996** [comment]
> 隔壁优化大师也有类似的评论，其实差不多是同一种问题，要么能新标签打开，要么能精准返回。 ![image](https://user-images.githubusercontent.com/18514089/210158878-554545f0-9abf-4d90-baa8-ae2287d8019f.png)

这两天更新下，加一个悬浮按钮【新标签页打开】

**Comment by maomao1996** [comment]
@zengruzhen 1.6.0 版本已支持【新标签页打开】和 【关闭悬浮菜单图标】功能

**Comment by zengruzhen** [comment]
> @zengruzhen 1.6.0 版本已支持【新标签页打开】和 【关闭悬浮菜单图标】功能

大佬
![image](https://user-images.githubusercontent.com/18514089/210303936-4e704517-8a0c-4fbe-8221-ba17ce64230d.png)
piji
![image](https://user-images.githubusercontent.com/18514089/210303938-085b4406-997d-4f4d-84e1-0d30f057c72e.png)
