### ISSUE TITLE
添加谷歌搜索重定向移除

### ISSUE THREAD

**Issue by CrazyboyQCD** [maomao1996/tampermonkey-scripts#13]
### 脚本

remove-redirect 跳转链接修复（移除重定向外链直达）

### 期望的功能是什么？

添加对谷歌搜索的重定向移除

### 这个功能解决了什么问题？

同上

**Comment by maomao1996** [comment]
能提供下会重定向的示例链接吗

**Comment by CrazyboyQCD** [comment]
> 能提供下会重定向的示例链接吗

https://www.google.com.hk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiE2PfKueWCAxXDk1YBHSMxCHsQFnoECBAQAQ&url=https%3A%2F%2Fzhuanlan.zhihu.com%2Fp%2F449787476&usg=AOvVaw2qX0w9AA-7BBwxrms5mKxo&opi=89978449

https://www.google.com.hk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiE2PfKueWCAxXDk1YBHSMxCHsQFnoECAoQAQ&url=https%3A%2F%2Fwww.ibm.com%2Fdocs%2Fzh%2Fopenxl-fortran-aix%2F17.1.0%3Ftopic%3Dcalls-assembler-level-subroutine-linkage-conventions&usg=AOvVaw0HLUGUqYJS88JHfv4PC_Fi&opi=89978449

**Comment by maomao1996** [comment]
2.3.0 已适配谷歌搜索
