### ISSUE TITLE
当有多页文件时, "删除空文件夹"功能无法找到不在当前页的空文件夹

### ISSUE THREAD

**Issue by kanoto** [maomao1996/tampermonkey-scripts#16]
### 脚本

115-helper 115 小助手

### 问题重现步骤

1. 找一个含有有很多文件的文件夹
2. 在后面的页面中, 找一个文件夹, 删掉里面所有东西变成一个空文件夹
3. 回到文件夹首页(第一页)
4. 使用"删除空文件夹"功能

### 实际的结果是什么？

显示无空文件夹

### 期望的结果是什么？

找到当前文件夹下, 后续页面里的空文件夹

### 操作系统

MacOS

### 浏览器

Chrome

### 扩展

暴力猴 Violentmonkey

**Comment by maomao1996** [comment]
第 2 点中的 “后面的页面” 是当前文件夹的分页，还是指新开的标签页

目前我这里还没有复现你这个问题

**Comment by kanoto** [comment]
> 第 2 点中的 “后面的页面” 是当前文件夹的分页，还是指新开的标签页
> 
> 目前我这里还没有复现你这个问题

是分页.
奇怪, 难道是偶发情况？还是因为我的那个文件夹里文件太多了... （大概3k个平行的文件夹, 其中一个是空文件夹）

**Comment by maomao1996** [comment]
> > 第 2 点中的 “后面的页面” 是当前文件夹的分页，还是指新开的标签页
> > 目前我这里还没有复现你这个问题
> 
> 是分页. 奇怪, 难道是偶发情况？还是因为我的那个文件夹里文件太多了... （大概3k个平行的文件夹, 其中一个是空文件夹）

如果文件量很大的话，可能是服务器数据缓存导致没有识别出空文件夹，毕竟空文件夹是根据 115 那边返回的文件夹大小来判断的

**Comment by kanoto** [comment]
> > > 第 2 点中的 “后面的页面” 是当前文件夹的分页，还是指新开的标签页
> > > 目前我这里还没有复现你这个问题
> > 
> > 
> > 是分页. 奇怪, 难道是偶发情况？还是因为我的那个文件夹里文件太多了... （大概3k个平行的文件夹, 其中一个是空文件夹）
> 
> 如果文件量很大的话，可能是服务器数据缓存导致没有识别出空文件夹，空文件夹是根据 115 那边返回的文件夹大小来判断的

原来如此, 我试一下等一段时间再执行.
