### ISSUE TITLE
How to use the script.

### ISSUE THREAD

**Issue by Lol0009q** [maomao1996/tampermonkey-scripts#17]
### 脚本

kill-watermark 杀死水印

### 问题重现步骤

I know nothing about programming, and i want to use this script to remove the watermark from bilibili manga chapters.
Could you tell me how to?
My email is adamegumi98@gmail.com 

### 实际的结果是什么？

I know nothing about programming, and i want to use this script to remove the watermark from bilibili manga chapters.
Could you tell me how to?
My email is adamegumi98@gmail.com 

### 期望的结果是什么？

I know nothing about programming, and i want to use this script to remove the watermark from bilibili manga chapters.
Could you tell me how to?
My email is adamegumi98@gmail.com 

### 操作系统

Windows

### 浏览器

Chrome

### 扩展

油猴 Tampermonkey

**Comment by maomao1996** [comment]
I'm sorry, this cannot be achieved
