### ISSUE TITLE
链滴(ld246.com)移除重定向

### ISSUE THREAD

**Issue by TCOTC** [maomao1996/tampermonkey-scripts#19]
### 脚本

remove-redirect 跳转链接修复（移除重定向外链直达）

### 期望的功能是什么？

例如 [这个帖子](https://ld246.com/article/1704204876718) 开头的链接：

`https://github.com/Yimien/plugin-memos-sync`

↓

`https://ld246.com/forward?goto=https%3A%2F%2Fgithub.com%2FYimien%2Fplugin-memos-sync`

![image](https://github.com/maomao1996/tampermonkey-scripts/assets/78434827/d79537d2-4f2a-4660-affc-c728174c6068)

### 这个功能解决了什么问题？

移除重定向

**Comment by TCOTC** [comment]
另外，[帖子](https://ld246.com/article/1704204876718) 可能需要登录后才能查看

**Comment by maomao1996** [comment]
已适配

**Comment by TCOTC** [comment]
感谢 (❁´ω`❁)
