### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by lunadefreunte** [maomao1996/tampermonkey-scripts#20]
### 脚本

kill-watermark 杀死水印

### 期望的功能是什么？

希望去掉sports.iqiyi.com
爱奇艺体育的水印！
多谢！

### 这个功能解决了什么问题？

去掉水印@@

**Comment by maomao1996** [comment]
看了一下，有一个右上角 log 需要去除，这个页面没有暂停的广告弹窗是吧

**Comment by maomao1996** [comment]
已适配
