### ISSUE TITLE
点击百度搜索中的`知乎`搜索结果条目下的子条目会跳转到与主条目一样的网址

### ISSUE THREAD

**Issue by CrazyboyQCD** [maomao1996/tampermonkey-scripts#21]
### 脚本

remove-redirect 跳转链接修复（移除重定向外链直达）

### 问题重现步骤

![image](https://github.com/maomao1996/tampermonkey-scripts/assets/53971641/7297e8f9-150e-4333-8bdf-988df70ebd21)
如上图，启动脚本后点击主条目（**实现简单的实时渲染器...**）下方的子条目（**ECS框架...**）时会跳转到主条目（**实现简单的实时渲染器...**）对应的网址

### 实际的结果是什么？

跳转到主条目对应的页面

### 期望的结果是什么？

跳转到所点击子条目对应的页面

### 操作系统

Windows

### 浏览器

Edge

### 浏览器版本（设置 — 关于）

123.0.2420.97

### 扩展

油猴 Tampermonkey

### 扩展版本

Tampermonkey v5.1.0

**Comment by maomao1996** [comment]
已修复
