### ISSUE TITLE
打开稿定设计的网页但是脚本未启动

### ISSUE THREAD

**Issue by Moeus** [maomao1996/tampermonkey-scripts#23]
### 脚本

kill-watermark 杀死水印

### 问题重现步骤

打开稿定设计的网页，插件没有见启动，随便打开网页内任意一个收费的模板，水印并没有去除

### 实际的结果是什么？

脚本未启动，并且水印未去除

### 期望的结果是什么？

期望脚本正常启动并且能去除水印

### 操作系统

Windows

### 浏览器

Edge

### 扩展

油猴 Tampermonkey

**Comment by maomao1996** [comment]
稿定设计已经修改了编辑器，现在是通过 `canvas` 来实现的，暂时不好去除了
