### ISSUE TITLE
搞定网站不好使了，是不是他们I修复了？

### ISSUE THREAD

**Issue by yujian410236643** [maomao1996/tampermonkey-scripts#24]
### 脚本

kill-watermark 杀死水印

### 问题重现步骤

搞定网站不好使了，是不是他们I修复了？

### 实际的结果是什么？

搞定网站不好使了，是不是他们I修复了？

### 期望的结果是什么？

搞定网站不好使了，是不是他们I修复了？

### 操作系统

Windows

### 浏览器

Edge

### 扩展

油猴 Tampermonkey

**Comment by maomao1996** [comment]
这个网站已失效，暂时不好去除了
