### ISSUE TITLE
稿定设计上的水印去除，貌似失效了

### ISSUE THREAD

**Issue by feifan2024** [maomao1996/tampermonkey-scripts#25]
### 脚本

kill-watermark 杀死水印

### 问题重现步骤

无

### 实际的结果是什么？

脚本没生效，水印依旧在

### 期望的结果是什么？

水印不出现

### 操作系统

Windows

### 浏览器

Chrome

### 扩展

油猴 Tampermonkey

### 扩展版本

Tampermonkey

**Comment by maomao1996** [comment]
该网站已实现
