### ISSUE TITLE
115指定目标文件夹查重

### ISSUE THREAD

**Issue by liuhangbin** [maomao1996/tampermonkey-scripts#26]
### 脚本

115-helper 115 小助手

### 期望的功能是什么？

请问可以支持115指定目标文件夹查重吗？  比如我有个目录 A 和 B, 我希望指定查询目录A中的文件是否在B中存在，如果存在则自动删除。

### 这个功能解决了什么问题？

应用场景是我有个库是刮削好的电影，电视剧。然后我接受了一个其他用户分享的文件夹，其中可能包含我已经刮削好的电影，我不想再浪费时间再刮削一遍了，如果可以直接查询我的库中已经有这个文件了，那么直接删除就可以了，谢谢。

**Comment by maomao1996** [comment]
这个场景目前小助手可以满足哦，用下面这两个方案

1. 把 AB 两个目录的文件放到一个目录下然后使用**单文件查重**
2. 在 A 目录下点击 **SHA1自动查重**

> 另外小助手都是通过唯一的 SHA1 来标识重复文件的

**Comment by maomao1996** [comment]
> > 这个场景目前小助手可以满足哦，用下面这两个方案
> > 
> > 1. 把 AB 两个目录的文件放到一个目录下然后使用**单文件查重**
> > 2. 在 A 目录下点击 **SHA1自动查重**
> 
> 自动查重会打开太多的页面。随便一个电视剧查重都能打开几十个页面，对于大量文件太耗费资源。而且没法自动删除。 是不是网页插件不太好实现？ 实在不行的话我还是老老实实写python 程序把...
> 
> 谢谢

那你可以用单文件夹查重，这个可以自动选中（需要在设置打开）再删除

网页插件可以实现，就是直接删的话容易误操作，就选择直接用官方的查重页面来进行二次确认，

打开太多页面这个就看看后面整调整了
