### ISSUE TITLE
百度自己的搜索结果未能去跳转

### ISSUE THREAD

**Issue by Xihihhh** [maomao1996/tampermonkey-scripts#27]
### 脚本

remove-redirect 跳转链接修复（移除重定向外链直达）

### 问题重现步骤

1. 访问[www.baidu.com](https://www.baidu.com)
2. 搜索`test`
3. 点击`test(英语单词) - 百度百科`

### 实际的结果是什么？

经过了[中间跳转](http://www.baidu.com/link?url=8zCgrev9u_WUxheJmzNk9xskMBLzSid1e1gXR20S8sI6RB2HJ-wxizHJifQZUKMdMGolFntga0Xi6FDUt9Dm8_)

### 期望的结果是什么？

百度自己的搜索结果去跳转

### 操作系统

Windows

### 浏览器

Edge

### 浏览器版本（设置 — 关于）

127.0.2651.98 (正式版本) (64 位)

### 扩展

油猴 Tampermonkey

### 扩展版本

Tampermonkey v5.1.1

**Comment by maomao1996** [comment]
百度自己的规则有点特殊，后面加一个兜底方案通过请求去拿原始链接

**Comment by maomao1996** [comment]
已修复
