### ISSUE TITLE
跳转链接修复-能否适配天眼查网站

### ISSUE THREAD

**Issue by wenruoa** [maomao1996/tampermonkey-scripts#31]
### 脚本

remove-redirect 跳转链接修复（移除重定向外链直达）

### 期望的功能是什么？

希望适配天眼查、企查查网站

### 这个功能解决了什么问题？

天眼查、企查查网站查询信息时必须要求登录账户，否则直接弹出登录界面，如果可以重新定向，免除了登录的烦恼

**Comment by maomao1996** [comment]
这个脚本是用来处理跳转拦截页（站外链接提示）的，不是用来处理登录拦截的
