### ISSUE TITLE
百度贴吧助手似乎不是所有帖子都能自动顶帖？

### ISSUE THREAD

**Issue by cbggh** [maomao1996/tampermonkey-scripts#5]
我在《大学吧》里的帖子没有显示自动回复的按钮，也不会触发自动回复

**Comment by maomao1996** [comment]
> 我在《大学吧》里的帖子没有显示自动回复的按钮，也不会触发自动回复

《大学吧》的帖子是旧版页面，已经做了兼容，更新最新版小助手就行
