### ISSUE TITLE
115助手 无法在油猴获取设置按扭

### ISSUE THREAD

**Issue by awe1** [maomao1996/tampermonkey-scripts#8]
单击油猴扩展，无法获取115助手脚本的设置按扭

**Comment by maomao1996** [comment]
> 单击油猴扩展，无法获取115助手脚本的设置按扭

使用的是什么浏览器，油猴插件的版本是多少

**Comment by awe1** [comment]
Vivaldi，最新版油猴，换了暴力猴插件也是一样

**Comment by maomao1996** [comment]
你试下这个版本看看
https://greasyfork.org/zh-CN/scripts/413142-115%E5%B0%8F%E5%8A%A9%E6%89%8B?version=1009364

**Comment by awe1** [comment]
还是没有。。。

**Comment by Jmirror4** [comment]
顶部增加链接任务的图标失效了 又藏在上传里面了

**Comment by maomao1996** [comment]
> 还是没有。。。

最新版在侧边栏新增了小助手设置按钮

**Comment by maomao1996** [comment]
> 顶部增加链接任务的图标失效了 又藏在上传里面了

最新版已经修复了

**Comment by awe1** [comment]
![截屏2022-11-02 19 50 25](https://user-images.githubusercontent.com/26203952/199482841-ac248fe7-be0b-486e-8d32-bad9d2c36686.png)
特意下载了Chrome试了试，发现还是没有下拉的设置按扭。。。😢

**Comment by awe1** [comment]
能不能在顶部添加一个按扭，弹出小窗口显示离线任务列表？新版115页面变成独立页面了使用起来很难受

**Comment by maomao1996** [comment]
> 能不能在顶部添加一个按扭，弹出小窗口显示离线任务列表？新版115页面变成独立页面了使用起来很难受

这个要研究下了

**Comment by awe1** [comment]
ok
